export const CLEAR_TIMEOUT_MS = 250;
export const STARTUP_TIMEOUT_MS = 15_000;
export const PLAYOUT_CONFIRM_TIMEOUT_MS = 30_000;
export const DEFAULT_TURN_ENDPOINT_TIMEOUT_MS = 3_000;
export const DEFAULT_TURN_MAX_DURATION_MS = 30_000;
